#!/bin/bash
#
#   Filename: mp42webm
#     Author: Synergiance
# Created On: 20 March 2018
#
# Easy way to use ffmpeg to convert to free codecs, without sacrificing
# quality.  You can type the command yourself really but I'm lazy and can't
# remember my commands well.  If you use this, please enjoy and make good
# use of it.

bin=$(which avconv)
if [[ $? -eq 1 ]]; then
    bin=$(which ffmpeg)
    if [[ $? -eq 1 ]]; then
        echo "ERROR: ffmpeg was not found on your system. exiting."
        exit 1
    fi
fi

$bin -i "$1" -acodec libvorbis -aq 5 -ac 2 -qmax 25 -threads 2 "${1%.mp4}.webm"
