#!/bin/bash
#
#   Filename: ytdl
# Created on: 10 Mar 2017
#     Author: Synergiance

bin=$(which ytdl)

if [[ $? -eq 1 ]]
then
    echo "Could not find main script"
    exit 1
fi

echo "This script is deprecated, please call ytdl directly"
exec $bin $@
